export const FETCH_ALL_ENTRIES = "FETCH_ALL_ENTRIES";
export const FETCH_ALL_ENTRIES_ERROR = "FETCH_ALL_ENTRIES_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const RESET_STATE = "RESET_STATE";


