// Home Page
export const FETCH_ALL_ENTRIES = "FETCH_ALL_ENTRIES";
export const FETCH_ALL_ENTRIES_ERROR = "FETCH_ALL_ENTRIES_ERROR";
export const UPDATE_SEARCH_INPUT = "UPDATE_SEARCH_INPUT";
export const CLEAR_HOME_PAGE_ERROR = "CLEAR_HOME_PAGE_ERROR";

// Create Edit View
export const UPDATE_WORKING_ENTRY = "UPDATE_WORKING_ENTRY";
export const FETCH_EXISTING_ENTRY = "FETCH_EXISTING_ENTRY";
export const FETCH_EXISTING_ENTRY_ERROR = "FETCH_EXISTING_ENTRY_ERROR";
export const CLEAR_CREATE_EDIT_ERROR = "CLEAR_CREATE_EDIT_ERROR";

// Common
export const RESET_STATE = "RESET_STATE";


